# Generated by Django 4.2.2 on 2023-08-23 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameoremail', models.CharField(default='Not Applicable', error_messages={'invalid': 'Please enter a valid username or email.', 'required': 'Please enter your username or email.'}, max_length=100)),
                ('password', models.CharField(error_messages={'invalid': 'Please enter a valid password.', 'mismatch': 'The password you entered is incorrect.', 'missing': 'Please enter your password.', 'none': 'Please enter your the correct details.', 'required': 'Please enter your password.'}, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', error_messages={'invalid': 'Please enter a valid username.', 'required': 'Please enter a username.', 'unique': 'This username is already taken.'}, max_length=100, unique=True)),
                ('email', models.EmailField(default='', error_messages={'invalid': 'Please enter a valid email.', 'required': 'Please enter an email.', 'unique': 'This email is already registered with us.'}, max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[!@#$%^&*()_\\-+=]).{8,20}$', code='invalid_password', message='Password must contain at least 1 uppercase letter, 1 lowercase letter, 1 digit, and 1 special character.')])),
                ('confirmpassword', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
