# Generated by Django 4.2.2 on 2023-08-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapplication', '0002_rename_first_name_feedback_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
