# Generated by Django 4.2.2 on 2023-08-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapplication', '0003_feedback_user_time_feedback_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_time',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_timezone',
        ),
    ]
